define([], function () {
  return {
    accuracy: 'Accuracy is {0}%',
    analysis: 'Analysis',
    classification: 'Classification',
    classResult: 'Guess: {0}, Actual: {1}',
    clear: 'Clear',
    close: 'Close',
    dataTransform: 'Data Transformation',
    errBothFeatures: 'Both selected features are the same.',
    errK: 'K can not be empty.',
    errLabelSel:
      "Label '{0}' is already selected as a feature. Please select another label.",
    errSelLabelType: "Selected label '{0}' must be a number type.",
    errFeatureSel:
      "Feature '{0}' is already selected as a label. Please select another feature.",
    errFeatureEmpty: "Feature '{0}' has empty value.",
    errFeatureXNumber: "Features (X-Axis) '{0}' must be a number type.",
    errFeatureYNumber: "Features (Y-Axis) '{0}' must be a number type.",
    errSelFeaturePls: 'Please select a feature.',
    errSelFeatureType: "Selected feature '{0}' must be a number type.",
    errFeatureValue: "Value of feature '{0}' must be a number.",
    errSelClassOrReg: 'Please select Analysis - Classification or Regression.',
    errSelLabelPls: 'Please select a label.',
    errSelFeatureX: 'Please select Features (X-Axis).',
    errSelFeatureY: 'Please select Features (Y-Axis).',
    errTrainingSet: 'Testing Set can not be  empty.',
    errTestingSetNum: 'Testing Set must be a number.',
    errTestingSenLess: 'Testing Set must be less than data length.',
    featureX: 'Features (X-Axis)',
    featureY: 'Features (Y-Axis)',
    features: 'Features',
    knnAnalysis: 'KNN Analysis',
    knnResult: "Click 'Run' to view KNN analysis results.",
    label: 'Label',
    minMax: 'Min-Max Normalization - (value−min)/(max−min)',
    minMaxAbbr: 'Min-Max',
    none: 'None',
    numberOfRec: 'Number of records:',
    numRecPerc: '% of records',
    prediction: 'Prediction',
    predResult: '{0} is {1}',
    regression: 'Regression',
    regResult: 'Guess: {0}, Actual: {1}, Error: {2}%',
    run: 'Run',
    selFeature: 'Select Feature',
    selFeatures: 'Select Features',
    selLabel: 'Select Label',
    tensorFlow: 'KNN Analysis with TensorFlow.js',
    test: 'Testing',
    testingSet: 'Testing Set',
    zscore: 'Z-Score Standardization - (value−μ)/σ',
    zscoreAbbr: 'Z-Score',
    wait: 'Wait...'
  }
})
